# Name of the workflow
name: Deploy React App to GitHub Pages

# Controls when the action will run. 
# This workflow runs on pushes to the 'main' branch.
on:
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-deploy"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions it needs to deploy to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Sets up Node.js for use in our workflow
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use a recent LTS version of Node.js

      # 3. Installs the project dependencies
      - name: Install dependencies
        run: npm install

      # 4. Builds the React app for production
      #    We add a PUBLIC_URL environment variable to ensure all asset paths are correct
      - name: Build
        run: npm run build
        env:
          PUBLIC_URL: /${{ github.event.repository.name }}

      # 5. Configures GitHub Pages for the deployment
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      # 6. Uploads the built application as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload the 'build' folder which contains the production app
          path: './build'

      # 7. Deploys the artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
